services:
  osiris-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: osiris-backend
    env_file:
      - .env.development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  docs:
    image: node:20-alpine
    container_name: osiris_docs
    working_dir: /app
    volumes:
      - ./docs:/app
      - docs_node_modules:/app/node_modules
      - docs_docusaurus:/app/.docusaurus
    ports:
      - "3000:3000"
    command: sh -c "npm install && rm -rf build node_modules/.cache && if [ -d .docusaurus ]; then find .docusaurus -mindepth 1 -exec rm -rf {} +; fi && npm start -- --host 0.0.0.0"

  postgres:
    image: postgres:15
    container_name: osiris-be_postgres
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - osiris-be_postgres_data:/var/lib/postgresql/data

volumes:
  osiris-be_postgres_data:
  docs_node_modules:
  docs_docusaurus:
